spring.application.name=cicd-ai-app

# Empêche DevTools de redémarrer l'appli quand le pipeline injecte des fichiers temporaires
spring.devtools.restart.exclude=**/temp_demo_only/**,**/Dockerfile.bad,**/*.md

# Expose l'endpoint Actuator Health pour la surveillance
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

gemini.model=gemini-2.5-pro
